[package]
name = "tam"
version = "0.1.7"
edition = "2021"
authors = ["wst7 <wstreet7@outlook.com>"]
description = "A tasks manager cli tool"
repository = "https://github.com/wst7/tam"
keywords = ["cli", "task", "todo", "manager"]
categories = ["command-line-utilities"]
license = "MIT OR Apache-2.0" 


[dependencies]
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
dirs = "5.0.1"
rustyline = "15.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
shlex = "1.3.0"
tabled = "0.17.0"
