[workspace]
name = "tam"
publish = true
git_release_enable = true
changelog_update = true
changelog_config = "cliff.toml"
pr_branch_prefix = "release-plz-"
pr_name = "Release {{ package }} v{{ version }}" # template for the PR name
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_allow_dirty = true # add `--allow-dirty` to `cargo publish`