# Every field in a theme file is optional.

# First come some various options
shadow = true  # Don't draw shadows around stacked views
borders = "simple"  # Alternatives are "none" and "outset"

# Here we define the color palette.
[colors]
    background = "#194a7a"
    # If the value is an array, the first valid color will be used.
    # If the terminal doesn't support custom color,
    # non-base colors will be skipped.
    shadow     = ["#a3b7ca"]
    view       = "#7593af"

    # Array and simple values have the same effect.
    primary   = ["#111111"]
    secondary = "#222222"
    tertiary  = "#444444"

    # Hex values can use lower or uppercase.
    # (base color MUST be lowercase)
    title_primary   = "#111111"
    title_secondary = "#222222"

    highlight = "#476f95"          # 滚动条滑块颜色
