name: Release

on:
  push:
    tags:
      - "v*" # 触发版本发布，比如 v1.0.0

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target=${{ matrix.target }}

      - name: Rename Binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/tam dist/${{ matrix.target }}${{ matrix.ext }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ matrix.target }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: build # 确保 build 完成后才执行
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
