name: Release Crate

on:
  push:
    branches:
      - main  # 当代码被推送到 main 分支时触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Rust 环境
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # 安装 cargo-release
    - name: Install cargo-release
      run: cargo install cargo-release

    # 发布 crate
    - name: Release new version
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo release patch --execute